version: '3'

services:
    neo4j:
        image: neo4j
        networks:
            - host
        ports:
            - 7474:7474
            - 7687:7687
        environment:
            - NEO4J_AUTH=neo4j/zeppelin
            - NEO4J_dbms_security_procedures_unrestricted=apoc.*
            - NEO4J_dbms_unmanagedExtensionClasses=semantics.extension=/rdf
        volumes:
            - C:/Users/a.santurbano/Desktop/zep-neo4j-gc2k18/neo4j/plugins:/plugins
            - C:/Users/a.santurbano/Desktop/zep-neo4j-gc2k18/neo4j/data:/data
    zeppelin:
        build:
            context: .
        image: santand84/zeppelin:0.8.0
        networks:
            - host
        ports:
            - 8080:8080
        volumes:
            - C:/Users/a.santurbano/Desktop/zep-neo4j-gc2k18/zeppelin/notebook:/zeppelin/notebook
            - C:/Users/a.santurbano/Desktop/zep-neo4j-gc2k18/zeppelin/conf:/zeppelin/conf
            - C:/Users/a.santurbano/Desktop/zep-neo4j-gc2k18/zeppelin/data:/zeppelin/spark-warehouse
networks:
    host: